version: '3.8'

services:
  store-service:
    image: boyone/toy-store-service:0.0.2
    build:
      context: store-service
      dockerfile: Dockerfile
    container_name: store-service
    ports:
      - '8000:8000'
    depends_on:
      - store-database
    restart: always
    environment:
      - TEST_MODE=true
      - BANK_GATEWAY=bank-gateway
      - SHIPPING_GATEWAY=shipping-gateway
      - DBCONNECTION=sealteam:sckshuhari@(store-database:3306)/toy
    networks:
      - backend

  store-database:
    image: mysql:8.0.22
    container_name: store-database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sealteam
      - MYSQL_PASSWORD=sckshuhari
      - MYSQL_DATABASE=toy
    volumes:
      - ./tearup/:/docker-entrypoint-initdb.d/
    ports:
      - '3306:3306'
    networks:
      - backend

  store-nginx:
    image: nginx:1.19.3-alpine
    container_name: store-nginx
    restart: always
    volumes:
      - ./html:/etc/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - store-service
    ports:
      - '80:80'

  bank-gateway:
    container_name: bank-gateway
    image: andyrbell/mountebank:2.3.2
    volumes:
      - ./bank-gateway/imposters.json:/imposters/imposters.json
    command:
      [
        'mb',
        'start',
        '--configfile',
        '/imposters/imposters.json',
        '--allowInjection',
      ]
    ports:
      - "8882:80"
    networks:
      - backend

  shipping-gateway:
    container_name: shipping-gateway
    image: andyrbell/mountebank:2.3.2
    volumes:
      - ./shipping-gateway/imposters.json:/imposters/imposters.json
    command:
      [
        'mb',
        'start',
        '--configfile',
        '/imposters/imposters.json',
        '--allowInjection',
      ]
    ports:
      - "8883:80"
    networks:
      - backend

networks:
  backend:
    name: mini-shopping-cart_default
    driver: bridge

